repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        stages: [ pre-commit ]
        language: system
        entry: flake8
        types: [ python ]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [ pre-commit ]
        language: system
        entry: make typechecks
        types: [ python ]

      - id: unittests
        name: unittests
        stages: [ pre-commit ]
        language: system
        entry: make unittests
        types: [ python ]

      - id: integration_tests
        name: integration_tests
        stages: [ pre-commit ]
        language: system
        entry: make integration_tests
        types: [ python ]