version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api/dockerfile
    image: api:v1
    container_name: api
    command:
#      bash -c "cd src && poetry run uvicorn --host 0.0.0.0 --port 8000 main:app --reload"
      bash -c "cd src && poetry run python main.py"
    networks:
      - backend
    ports:
      - '8080:8000'
    env_file:
      - .env/.api.env
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
#    restart: unless-stopped
    depends_on:
      - db

  db:
    image: emurze/testdb_postgres:16
    container_name: db
    networks:
      - backend
    ports:
      - '5432:5432'
    env_file:
      - .env/.db.env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:

networks:
  backend:
