version: "3.8"
services:
  api:
    build: .
    image: api:v1
    container_name: furniture_shop.api
    command:
      bash -c "cd src && poetry run uvicorn --host 0.0.0.0 --port 8000 api.app:app --reload"
    networks:
      - backend
    ports:
      - '8080:8000'
    env_file:
      - sample/.app.env
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: emurze/testdb_postgres:16
    container_name: trading.db
    networks:
      - backend
    ports:
      - '5432:5432'
    env_file:
      - sample/.db.env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:

networks:
  backend:
