name: Furniture shop CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install flake8
        run: |
          pip install flake8

      - name: Lint with flake8
        run: |
          make ci_lint

  type-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install mypy
        run: |
          pip install mypy
          pip install pydantic
          pip install sqlalchemy

      - name: Check types with mypy
        run: |
          make ci_typechecks

  unit-tests:
    needs: [lint, type-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install flake8
        run: |
          pip install pytest
          pip install pydantic

      - name: Lint with flake8
        run: |
           make ci_unittests

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    services:
      db:
        image: emurze/testdb_postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_furniture_shop
          POSTGRES_USER: test_adm1
          POSTGRES_PASSWORD: 12345678
    env:
      DB_NAME: suppress
      DB_USER: suppress
      DB_PASS: 12345
      DB_HOST: suppress
      DB_PORT: 12345
      TEST_DB_NAME: test_furniture_shop
      TEST_DB_USER: test_adm1
      TEST_DB_PASS: 12345678
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 5432
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install poetry==1.7.1
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run Tests
        run: |
          make ci_integration_tests